spring:
  application:
    name: warehouse
  config:
    activate:
      profile:
        on-profile: ci
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6541/smart_home
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:./schema.sql

server:
  port: 0

logging:
  level:
    org:
      springframework: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/