spring.application.name=analyzer

spring.config.activate.profile.on-profile=ci

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.enable-auto-commit=false

spring.kafka.hub-consumer.topic=telemetry.hubs.v1
spring.kafka.hub-consumer.group-id=analyzer-hub-group
spring.kafka.hub-consumer.value-deserializer=ru.yandex.practicum.kafka.deserializer.HubEventDeserializer
spring.kafka.hub-consumer.max-poll-records=100
spring.kafka.hub-consumer.auto-offset-reset=earliest

spring.kafka.snapshot-consumer.topic=telemetry.snapshots.v1
spring.kafka.snapshot-consumer.group-id=analyzer-snapshot-group
spring.kafka.snapshot-consumer.value-deserializer=ru.yandex.practicum.kafka.deserializer.SnapshotDeserializer
spring.kafka.snapshot-consumer.max-poll-records=100
spring.kafka.snapshot-consumer.auto-offset-reset=earliest

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:6541/smart_home
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:./schema.sql

grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.enableKeepAlive=true
grpc.client.hub-router.keepAliveWithoutCalls=true
grpc.client.hub-router.negotiationType=plaintext

logging.level.ru.yandex.practicum=DEBUG
logging.level.org.apache.kafka=WARN
logging.level.org.springframework=ERROR


